class WeaponShops {
    class gun {
        name = "Sklep z Bronia";
        side = "civ";
        conditions = "license_civ_gun";
        items[] = {
            {
                "hgun_Rook40_F",
                "",
                40000,
                -1,
                ""
            },
            {
                "hgun_ACPC2_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                35000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                40000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                300,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                5000,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                150,
                -1,
                ""
            },
            {
                "10Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                125,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "acc_flashlight_pistol",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_ACO_grn_smg",
                "",
                2500,
                -1,
                ""
            },
        };
    };
    class gang {
        name = "Sklep z bronią";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "hgun_Rook40_F",
                "",
                9000,
                -1,
                ""
            },
            {
                "hgun_ACPC2_F",
                "",
                10000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                11000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                13000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                150,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                300,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                5000,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                150,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                125,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "acc_flashlight_pistol",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_ACO_grn_smg",
                "",
                2500,
                -1,
                ""
            },
        };
    };
    class rebel {
        name = "Sklep u Komandora";
        side = "civ";
        conditions = "license_civ_rebel";
        items[] = {
            {
                "Medikit",
                "",
                15000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                1200,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                4500,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                500,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                5000,
                -1,
                ""
            },
            {
                "hgun_ACPC2_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                35000,
                -1,
                ""
            },
            {
                "hgun_Rook40_F",
                "",
                40000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                40000,
                -1,
                ""
            },
            {
                "arifle_AKS_F",
                "",
                70000,
                "-1",
                ""
            },
            {
                "arifle_MXC_F",
                "",
                140000,
                "-1",
                ""
            },
            {
                "srifle_DMR_01_DMS_BI_F",
                "",
                170000,
                "-1",
                "license_civ_rebel2"
            },
            {
                "srifle_DMR_07_hex_F",
                "",
                140000,
                "-1",
                "license_civ_rebel2"
            },
            {
                "arifle_MX_F",
                "",
                150000,
                "-1",
                "license_civ_rebel2"
            },
            {
                "arifle_MXM_F",
                "",
                180000,
                "-1",
                "license_civ_rebel3"
            },
            {
                "LMG_03_F",
                "",
                280000,
                "-1",
                "license_civ_rebel3"
            },
            {
                "srifle_DMR_03_khaki_F",
                "",
                320000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MX_SW_F",
                "",
                180000,
                "-1",
                "license_civ_rebel4"
            },
            {
                "arifle_SDAR_F",
                "",
                65000,
                -1,
                ""
            },
            {
                "arifle_TRG20_F",
                "",
                80000,
                -1,
                ""
            },
            {
                "arifle_TRG21_F",
                "",
                78000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_Mk20_F",
                "",
                76600,
                -1,
                ""
            },
            {
                "arifle_Mk20C_F",
                "",
                76500,
                -1,
                ""
            },
            {
                "SMG_03_hex",
                "",
                110000,
                -1,
                ""
            },
            {
                "SMG_03_TR_hex",
                "",
                105000,
                -1,
                "license_civ_rebel2"
            },
            {
                "SMG_03C_khaki",
                "",
                105000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_Katiba_F",
                "",
                100000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_CTAR_hex_F",
                "",
                120000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_SPAR_01_khk_F",
                "",
                82000,
                -1,
                ""
            },
            {
                "arifle_CTARS_hex_F",
                "",
                55000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_MSBS65_black_F",
                "",
                115000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_MSBS65_Mark_black_F",
                "",
                130000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_AK12U_lush_F",
                "",
                170000,
                -1,
                "license_civ_rebel3"
            },
            {
                "srifle_DMR_03_multicam_F",
                "",
                180000,
                -1,
                "license_civ_rebel3"
            },
            {
                "srifle_DMR_06_camo_F",
                "",
                160000,
                -1,
                ""
            },
            {
                "arifle_AK12_F",
                "",
                240000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_AKM_F",
                "Hunter 7.62 mm",
                75000,
                -1,
                ""
            },
            {
                "srifle_EBR_F",
                "",
                250000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_SPAR_03_khk_F",
                "",
                290500,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_RPK12_F",
                "",
                240000,
                -1,
                "license_civ_rebel4"
            },
            {
                "LMG_Mk200_F",
                "",
                575000,
                -1,
                "license_civ_rebel4"
            },
            {
                "launch_RPG7_F",
                "",
                750000,
                -1,
                ""
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                50000,
                -1,
                ""
            },
            {
                "launch_RPG32_F",
                "",
                750000,
                -1,
                "license_civ_rebel3"
            }
        };
        mags[] = {
            {
                "30Rnd_556x45_Stanag",
                "",
                175,
                -1,
                ""
            },
            {
                "10Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                140,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                150,
                -1,
                ""
            },
            {
                "16Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                150,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                140,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                140,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag_Tracer",
                "",
                280,
                -1,
                ""
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                280,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                280,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                280,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green_mag_Tracer",
                "",
                280,
                -1,
                ""
            },
            {
                "10Rnd_762x54_Mag",
                "",
                450,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_762x51_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_580x42_Mag_Tracer_F",
                "",
                210,
                -1,
                ""
            },
            {
                "30Rnd_762x39_AK12_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_762x39_AK12_Mag_Tracer_Green_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                175,
                -1,
                ""
            },
            {
                "100Rnd_580x42_Mag_Tracer_F",
                "",
                750,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                750,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag_Tracer",
                "",
                750,
                -1,
                ""
            },
            {
                "200Rnd_65x39_cased_Box_Tracer_Tracer_Red",
                "",
                750,
                -1,
                ""
            },
            {
                "150Rnd_762x54_Box_Tracer",
                "",
                750,
                -1,
                ""
            },
            {
                "RPG7_F",
                "",
                100000,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_762x51_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                1500,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "200Rnd_65x39_cased_Box_Tracer",
                "",
                1000,
                -1,
                ""
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_762x39_AK12_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                100,
                -1,
                ""
            },
            {
                "10Rnd_93x64_DMR_05_Mag",
                "",
                10000,
                -1,
                ""
            },
            {
                "10Rnd_338_Mag",
                "",
                5000,
                -1,
                ""
            },
            {
                "150Rnd_762x51_Box_Tracer",
                "",
                15000,
                -1,
                ""
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                1000,
                -1,
                ""
            },
            {
                "RPG32_F",
                "",
                200000,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                600,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                990,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                700,
                -1,
                ""
            },
            {
                "muzzle_snds_acp",
                "",
                1500,
                -1,
                ""
            },
            {
                "muzzle_snds_L",
                "",
                1500,
                -1,
                ""
            },
            {
                "optic_ERCO_blk_F",
                "",
                3100,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                3100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                990,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                1000,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                400,
                -1,
                ""
            },
            {
                "optic_Arco_blk_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "optic_AMS",
                "",
                7000,
                -1,
                "license_civ_rebel3"
            },
            {
                "optic_DMS",
                "",
                4500,
                -1,
                "license_civ_rebel3"
            },
            {
                "optic_KHS_blk",
                "",
                7500,
                -1,
                "license_civ_rebel4"
            },
        };
    };
    class donatorgun {
        name = "Sklep Donatora";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "Medikit",
                "",
                15000,
                -1,
                "call life_donator >= 1"
            },
            {
                "Binocular",
                "",
                1200,
                -1,
                "call life_donator >= 1"
            },
            {
                "ItemGPS",
                "",
                4500,
                -1,
                "call life_donator >= 1"
            },
            {
                "ItemMap",
                "",
                500,
                -1,
                "call life_donator >= 1"
            },
            {
                "ItemCompass",
                "",
                500,
                -1,
                "call life_donator >= 1"
            },
            {
                "ItemWatch",
                "",
                500,
                -1,
                "call life_donator >= 1"
            },
            {
                "ItemRadio",
                "",
                500,
                -1,
                "call life_donator >= 1"
            },
            {
                "FirstAidKit",
                "",
                900,
                -1,
                "call life_donator >= 1"
            },
            {
                "NVGoggles",
                "",
                900,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_ACPC2_F",
                "",
                3500,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                3500,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                3500,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Rook40_F",
                "",
                3500,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_05_F",
                "",
                22500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "SMG_02_F",
                "",
                27500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "SMG_01_F",
                "",
                18500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_AKS_F",
                "",
                40000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_SPAR_01_khk_F",
                "",
                45000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_SPAR_01_snd_F",
                "",
                50000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_Mk20_F",
                "",
                50000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_Mk20_plain_F",
                "",
                50000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_TRG20_F",
                "",
                50000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_SPAR_02_khk_F",
                "",
                45000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_SPAR_02_snd_F",
                "",
                45000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_Mk20C_F",
                "",
                45000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_Mk20C_plain_F",
                "",
                45000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_TRG21_F",
                "",
                55000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_CTAR_ghex_F",
                "",
                60000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_CTAR_hex_F",
                "",
                60000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "srifle_DMR_07_ghex_F",
                "",
                65000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "srifle_DMR_07_hex_F",
                "",
                65000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_MXC_F",
                "",
                60000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_MXC_khk_F",
                "",
                90000,
                "-1",
                "call life_donator >= 1"
            },
            {
                "arifle_Katiba_F",
                "",
                85000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "LMG_03_F",
                "",
                120000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_ARX_hex_F",
                "",
                65000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_ARX_ghex_F",
                "",
                65000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MX_F",
                "",
                75000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MX_khk_F",
                "",
                75000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MXM_F",
                "",
                85000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MXM_khk_F",
                "",
                85000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MX_SW_F",
                "",
                120000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MX_SW_khk_F",
                "",
                120000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_F",
                "",
                75000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_sand_F",
                "",
                75000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_camo_F",
                "",
                75000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_Mark_camo_F",
                "",
                100000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_Mark_sand_F",
                "",
                100000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_MSBS65_Mark_F",
                "",
                100000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "LMG_Mk200_F",
                "",
                300000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_AK12_lush_F",
                "",
                140000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_AK12_arid_F",
                "",
                140000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_AKM_F",
                "",
                95000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_AKM_FL_F",
                "",
                95000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_AK12U_F",
                "",
                90000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_AK12U_lush_F",
                "",
                90000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_AK12U_arid_F",
                "",
                90000,
                "-1",
                "call life_donator >= 2"
            },
            {
                "arifle_RPK12_F",
                "",
                320000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_RPK12_lush_F",
                "",
                320000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_RPK12_arid_F",
                "",
                320000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_03_khaki_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_03_tan_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_03_multicam_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_03_woodland_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_06_camo_F",
                "",
                130000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_06_olive_F",
                "",
                130000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_EBR_F",
                "",
                150000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "srifle_DMR_01_F",
                "",
                130000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_SPAR_03_khk_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "arifle_SPAR_03_snd_F",
                "",
                180000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                80000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "launch_RPG32_F",
                "",
                400000,
                "-1",
                "call life_donator >= 1"
            }
        };
        mags[] = {
            {
                "30Rnd_556x45_Stanag",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                140,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                150,
                -1,
                ""
            },
            {
                "16Rnd_9x21_Mag",
                "",
                150,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                150,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_556x45_Stanag_Tracer_Yellow",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_556x45_Stanag_green",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                1500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_580x42_Mag_F",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_580x42_Mag_Tracer_F",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                300,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_545x39_Mag_Green_F",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                500,
                "-1",
                "call life_donator >= 1"
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "30Rnd_65x39_caseless_khaki_mag",
                "",
                500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "30Rnd_762x39_AK12_Lush_Mag_F",
                "",
                500,
                "-1",
                "call life_donator >= 3"
            },
            {
                "30Rnd_762x39_AK12_Lush_Mag_Tracer_F",
                "",
                500,
                "-1",
                "call life_donator >= 3"
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "30Rnd_762x39_Mag_Green_F",
                "",
                500,
                "-1",
                "call life_donator >= 3"
            },
            {
                "30Rnd_762x39_AK12_Mag_F",
                "",
                500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                1500,
                "-1",
                "call life_donator >= 2"
            },
            {
                "20Rnd_762x51_Mag",
                "",
                1000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                500,
                "-1",
                "call life_donator >= 3"
            },
            {
                "200Rnd_65x39_cased_Box_Tracer",
                "",
                3000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "200Rnd_65x39_cased_Box_Tracer_Tracer_Red",
                "",
                3000,
                "-1",
                "call life_donator >= 3"
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                750,
                "-1",
                "call life_donator >= 3"
            },
            {
                "2Rnd_12Gauge_Slug",
                "",
                750,
                "-1",
                "call life_donator >= 3"
            },
            {
                "RPG32_F",
                "",
                150000,
                "-1",
                "call life_donator >= 3"
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                600,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                500,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                990,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                700,
                -1,
                ""
            },
            {
                "muzzle_snds_acp",
                "",
                1500,
                -1,
                ""
            },
            {
                "muzzle_snds_L",
                "",
                1500,
                -1,
                ""
            },
            {
                "optic_ERCO_blk_F",
                "",
                3100,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                3100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                990,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                1000,
                -1,
                ""
            },
            {
                "optic_DMS",
                "",
                4500,
                -1,
                ""
            },
            {
                "optic_Arco_blk_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "optic_AMS",
                "",
                7000,
                -1,
                ""
            },
            {
                "optic_KHS_blk",
                "",
                7500,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                400,
                -1,
                ""
            }
        };
    };
    class genstore {
        name = "Sklep Techniczny";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                1200,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                4500,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                500,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1100,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                5000,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
    class f_station_store {
        name = "Stacja Benzynowa";
        side = "";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                1200,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                4500,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                500,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                500,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                5000,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
    class cop_basic {
        name = "Sklep Policyjny";
        side = "cop";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                1,
                -1,
                ""
            },
            {
                "Rangefinder",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                1,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1,
                -1,
                ""
            },
            {
                "NVGoggles_OPFOR",
                "",
                1,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                1000,
                -1,
                ""
            },
            {
                "HandGrenade_Stone",
                "Flashbang",
                3000,
                -1,
                ""
            },
            {
                "SmokeShellBlue",
                "Gaz łzawiący",
                3000,
                -1,
                ""
            },
            {
                "hgun_P07_snds_F",
                "Paralizator",
                3000,
                -1,
                ""
            },
            {
                "SMG_01_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "SMG_02_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "SMG_05_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "arifle_SDAR_F",
                "",
                5000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "arifle_TRG21_F",
                "",
                5000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "arifle_Mk20_F",
                "",
                5000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "SMG_03_black",
                "",
                5000,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                15000,
                -1,
                "call life_coplevel >=9"
            },
            {
                "arifle_SPAR_01_blk_F",
                "",
                5000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "arifle_SPAR_02_blk_F",
                "",
                5000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "LMG_03_F",
                "",
                30000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "arifle_CTARS_blk_F",
                "",
                8500,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "arifle_MX_Black_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "arifle_MX_SW_Black_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "arifle_MXM_Black_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "arifle_MSBS65_black_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "arifle_MSBS65_Mark_black_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "arifle_MSBS65_UBS_black_F",
                "",
                20000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "srifle_DMR_07_blk_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "arifle_ARX_blk_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "arifle_Katiba_F",
                "",
                10000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "LMG_Mk200_black_F",
                "",
                45000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "srifle_EBR_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "srifle_DMR_03_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "arifle_SPAR_03_blk_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "srifle_DMR_06_olive_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "arifle_AK12U_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "arifle_AK12_F",
                "",
                25000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "arifle_RPK12_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "srifle_DMR_05_blk_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 4 && license_cop_sniper "
            },
            {
                "launch_RPG32_ghex_F",
                "",
                100000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "launch_NLAW_F",
                "",
                200000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                500,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 5"
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_556x45_Box_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_65x39_cased_Box",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_762x51_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_HE_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "NLAW_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_93x64_DMR_05_Mag",
                "",
                10000,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                "call life_coplevel >=1"
            },
            {
                "2Rnd_12Gauge_Slug",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            },
            {
                "6Rnd_12Gauge_Pellets",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            },
        };
        accs[] = {
            {
                "optic_Aco",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Holosight",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Holosight_smg",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_ACO_grn_smg",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Arco_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Hamr",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_MRCO",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_ERCO_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_DMS",
                "",
                100,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "optic_AMS",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "optic_KHS_blk",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "muzzle_snds_acp",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_L",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_M",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_570",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_H",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_58_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_65_TI_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_B",
                "",
                100,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "muzzle_snds_93mmg",
                "",
                500,
                -1,
                "call life_coplevel >= 4"
            }
        };
    };
    class swat_basic {
        name = "Sklep SWAT";
        side = "cop";
        conditions = "license_cop_cSwat";
        items[] = {
            {
                "Binocular",
                "",
                1,
                -1,
                ""
            },
            {
                "Rangefinder",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                1,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1,
                -1,
                ""
            },
            {
                "NVGoggles_OPFOR",
                "",
                1,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                5000,
                -1,
                ""
            },
            {
                "HandGrenade_Stone",
                "Flashbang",
                5000,
                -1,
                ""
            },
            {
                "SmokeShellBlue",
                "Gaz łzawiący",
                5000,
                -1,
                ""
            },
            {
                "SmokeShellPurple",
                "",
                1,
                -1,
                ""
            },
            {
                "hgun_P07_snds_F",
                "Paralizator",
                5000,
                -1,
                ""
            },
            {
                "arifle_SDAR_F",
                "",
                48750,
                -1,
                ""
            },
            {
                "arifle_MX_SW_Black_F",
                "",
                130500,
                -1,
                ""
            },
            {
                "arifle_MXM_Black_F",
                "",
                `135000,
                -1,
                ""
            },
            {
                "arifle_AK12U_lush_F",
                "",
                127500,
                -1,
                ""
            },
            {
                "arifle_AK12U_arid_F",
                "",
                127500,
                -1,
                ""
            },
            {
                "arifle_AKM_FL_F",
                "Magi do AK-12",
                9999999,
                -1,
                ""
            },
            {
                "arifle_ARX_blk_F",
                "",
                130000,
                -1,
                ""
            },
            {
                "arifle_ARX_ghex_F",
                "",
                130000,
                -1,
                ""
            },
            {
                "arifle_ARX_hex_F",
                "",
                130000,
                -1,
                ""
            },
            {
                "srifle_DMR_03_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "srifle_DMR_03_khaki_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "srifle_DMR_03_tan_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "srifle_DMR_03_multicam_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "srifle_DMR_03_woodland_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "arifle_AK12_F",
                "",
                180000,
                -1,
                ""
            },
            {
                "arifle_AK12_lush_F",
                "",
                180000,
                -1,
                ""
            },
            {
                "arifle_AK12_arid_F",
                "",
                180000,
                -1,
                ""
            },
            {
                "arifle_AK12_GL_arid_F",
                "",
                190000,
                -1,
                ""
            },
            {
                "arifle_AK12_GL_lush_F",
                "",
                190000,
                -1,
                ""
            },
            {
                "arifle_AK12_GL_F",
                "",
                190000,
                -1,
                ""
            },
            {
                "LMG_Mk200_black_F",
                "",
                262000,
                -1,
                ""
            },
            {
                "LMG_Mk200_F",
                "",
                262000,
                -1,
                ""
            },
            {
                "arifle_SPAR_03_blk_F",
                "",
                217500,
                -1,
                ""
            },
            {
                "LMG_03_F",
                "",
                210000,
                -1,
                ""
            },
            {
                "arifle_MSBS65_black_F",
                "",
                86250,
                -1,
                ""
            },
            {
                "arifle_MSBS65_sand_F",
                "",
                86250,
                -1,
                ""
            },
            {
                "arifle_MSBS65_Mark_black_F",
                "",
                97500,
                -1,
                ""
            },
            {
                "arifle_MSBS65_Mark_sand_F",
                "",
                97500,
                -1,
                ""
            },
            {
                "arifle_MSBS65_Mark_camo_F",
                "",
                97500,
                -1,
                ""
            },
            {
                "arifle_MSBS65_UBS_black_F",
                "",
                105000,
                -1,
                ""
            },
            {
                "arifle_MSBS65_UBS_sand_F",
                "",
                105000,
                -1,
                ""
            },
            {
                "arifle_MSBS65_UBS_camo_F",
                "",
                105000,
                -1,
                ""
            },
            {
                "srifle_DMR_06_olive_F",
                "",
                210000,
                -1,
                ""
            },
            {
                "srifle_DMR_06_camo_F",
                "",
                210000,
                -1,
                ""
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                37500,
                -1,
                ""
            },
            {
                "arifle_RPK12_F",
                "",
                270000,
                -1,
                ""
            },
            {
                "arifle_RPK12_lush_F",
                "",
                270000,
                -1,
                ""
            },
            {
                "arifle_RPK12_arid_F",
                "",
                270000,
                -1,
                ""
            },
            {
                "srifle_DMR_05_blk_F",
                "",
                310000,
                -1,
                ""
            },
            {
                "launch_RPG32_ghex_F",
                "",
                562500,
                -1,
                ""
            },
            {
                "launch_NLAW_F",
                "",
                400000,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                100,
                -1,
                ""
            },
            {
                "200Rnd_65x39_cased_Box",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_762x51_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "10Rnd_50BW_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "200Rnd_65x39_cased_Box",
                "",
                100,
                -1,
                ""
            },
            {
                "150Rnd_762x54_Box",
                "",
                100,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "RPG32_F",
                "",
                1000,
                -1,
                ""
            },
            {
                "RPG32_HE_F",
                "",
                1000,
                -1,
                ""
            },
            {
                "NLAW_F",
                "",
                1000,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                100,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                ""
            },
            {
                "10Rnd_93x64_DMR_05_Mag",
                "",
                1000,
                -1,
                ""
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "1Rnd_SmokeBlue_Grenade_shell",
                "Cyklon B",
                1000,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "muzzle_snds_L",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_M",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_H",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_ACO_grn_smg",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_B",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Arco_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_ERCO_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_DMS",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_AMS",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_LRPS",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_KHS_blk",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_65_TI_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_93mmg",
                "",
                500,
                -1,
                ""
            },
            {
                "muzzle_snds_338_black",
                "",
                500,
                -1,
                ""
            },
            {
                "muzzle_snds_570",
                "",
                100,
                -1,
                ""
            }
        };
    };
    class med_basic {
        name = "Sklep Medyczny";
        side = "med";
        conditions = "";
        items[] = {
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                150,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                125,
                -1,
                ""
            },
            {
                "NVGoggles_INDEP",
                "",
                200,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                175,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
};