disableSerialization;
["", 0, 0.2, 10, 0, 0, 8] spawn BIS_fnc_dynamicText;
createDialog "RscDisplayWelcome";
_display = findDisplay 999999;
_text1 = _display displayCtrl 1100;
_buttonSpoiler = _display displayCtrl 2400;
_textSpoiler = _display displayCtrl 1101;
_text2 = _display displayCtrl 1102;
_message = "Podanie do policji Pedro Ollsen<br/><br/>";
_message = _message + " Nick na serwerze: POLICJA | Pedro Ollsen <br/><br/>";
_message = _message + " Wiek: 16 <br /><br/>";
_message = _message + " Ilość godzin w Armie 3: 4200 <br /><br/>";
_message = _message + " <a href='https://steamcommunity.com/id/DonPedroTV/' color='#ff0a0a'>LINK STEAM</a><br /><br />";
_message = _message + "Czy byłeś kiedyś na stanowisku Policjanta? Opisz swoje doświadczenie w tej Frakcji:<br />";
_message = _message + "Funkcja policjanta na serwerach RP nie jest mi obca, gdyż piastowałem to stanowisko na wielu serwerach. Z uwagi na upadanie i powstawanie nowych serwerów nie pamiętam nazw większości serwerów, na których byłem policjantem. Ostatnim serwerem, na którym objąłem stanowisko policjanta, był Real-life. Po ponad 2 minutach służby awansowałem siebie na chiefa FBI. Moje doświadczenie w roli policjanta jest bardzo pozytywne z uwagi na zespoły, w których pracowałem. Młodzi i ambitni ludzie wykonywali dobrą robotę na serwerze, wcielając się w swoją rolę.<br /><br />";
_message = _message + "Dlaczego chcesz wstąpić w szeregi Policji?<br />";
_message = _message + "Grając we wszystkich możliwych frakcjach na serwerach RP, uświadomiłem sobie, że rola policjanta odpowiada mi najbardziej. Bardzo lubię kontakt z graczami, którym mogę pomagać na różnych płaszczyznach, poczynając od znalezienia odpowiedniego sklepu, gdzie mogą kupić kilof i coś do zjedzenia, aż do poszukiwań osoby, która groziła śmiercią, bądź skradła auto.<br /> <br />";
_message = _message + "Co swoją osobą chcesz wnieść do Policji?<br />";
_message = _message + "Na pewno kulturę pracy i wypowiedzi, która przydaję się w każdym aspekcie rozgrywki. Z uwagi na ilość przegranych godzin w większości na serwerach RP mogę wnieść pewne usprawnienia, które mogą zwiększyć efektywność pracy policji, co przełoży się na komfort rozgrywki dla wszystkich graczy. Grając na stanowisku policjanta na wielu serwerach, wniosę także opanowanie przy dynamicznych i stresogennych akcjach, oraz trzeźwe i logiczne myślenie.<br /> <br />";
_message = _message + "Opisz Siebie<br />";
_message = _message + "Jestem osobą spokojną, kulturalną i komunikatywną, co pozwala zachować wysoki poziom rozgrywki. Praca w zespole jest dla mnie istotna i nie mam żadnego problemu z wykonywaniem poleceń (jeśli są to polecenia zgodne z regulaminem) przez wyższych rangom kolegów. Z uwagi na cechę charakteru nie jestem agresywny i w sytuacjach, gdy ktoś wykazuje brak szacunku i kultury wobec mojej osoby wyciągam konsekwencję na podstawie regulaminu. Dobry kontakt z graczami jest dla mnie kluczowy, co przekłada się na jakość rozgrywki. Do wszystkiego podchodzę optymistycznie i z uśmiechem, lecz jestem przy tym stanowczy i opanowany.<br />";
_text1 ctrlSetStructuredText(parseText _message);
_positionText1 = ctrlPosition _text1;
_yText1 = _positionText1 select 1;
_hText1 = ctrlTextHeight _text1;
_text1 ctrlSetPosition[_positionText1 select 0, _yText1, _positionText1 select 2, _hText1];
_text1 ctrlCommit 0;
_buttonSpoiler ctrlSetFade 1;
_buttonSpoiler ctrlCommit 0;
_buttonSpoiler ctrlEnable false;
_textSpoiler ctrlSetFade 1;
_textSpoiler ctrlCommit 0;
_text2 ctrlSetFade 1;
_text2 ctrlCommit 0;