class WeaponShops {
    class gun {
        name = "Sklep z Bronia";
        side = "civ";
        conditions = "license_civ_gun";
        items[] = {
            {
                "hgun_ACPC2_F",
                "",
                18000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                23000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                18000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "hgun_Rook40_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "SMG_01_F",
                "",
                60000,
                -1,
                "license_civ_gun_2"
            },
            {
                "SMG_02_F",
                "",
                45000,
                -1,
                "license_civ_gun_2"
            },
            {
                "SMG_05_F",
                "",
                60000,
                -1,
                "license_civ_gun_2"
            },
            {
                "hgun_PDW2000_F",
                "",
                30000,
                -1,
                "license_civ_gun_2"
            },
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                500,
                -1,
                ""
            },
            {
                "10Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                500,
                -1,
                "license_civ_gun_2"
            },
            {
                "30Rnd_9x21_Yellow_Mag",
                "",
                500,
                -1,
                "license_civ_gun_2"
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                500,
                -1,
                "license_civ_gun_2"
            }
        };
        accs[] = {
            {
                "acc_flashlight_pistol",
                "",
                750,
                -1,
                ""
            },
            {
                "optic_ACO_grn_smg",
                "",
                5000,
                -1,
                "license_civ_gun_2"
            },
            {
                "optic_ACO_grn",
                "",
                5000,
                -1,
                "license_civ_gun_2"
            },
            {
                "optic_Aco",
                "",
                5000,
                -1,
                "license_civ_gun_2"
            },
            {
                "optic_Aco_smg",
                "",
                5000,
                -1,
                "license_civ_gun_2"
            },
        };
    };
    class gang {
        name = "Sklep z bronią";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "hgun_ACPC2_F",
                "",
                18000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                23000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                18000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "hgun_Rook40_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                500,
                -1,
                ""
            },
            {
                "10Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
        };
        accs[] = {
            {
                "acc_flashlight_pistol",
                "",
                750,
                -1,
                ""
            },
        };
    };
    class rebel {
        name = "Sklep u Komandora";
        side = "civ";
        conditions = "license_civ_rebel";
        items[] = {
            {
                "Medikit",
                "",
                25000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            },
            {
                "hgun_ACPC2_F",
                "",
                9000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                11500,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                9000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                10000,
                -1,
                ""
            },
            {
                "hgun_Rook40_F",
                "",
                10000,
                -1,
                ""
            },
            {
                "SMG_01_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "SMG_02_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "SMG_05_F",
                "",
                30000,
                -1,
                ""
            },
            {
                "hgun_PDW2000_F",
                "",
                15000,
                -1,
                ""
            },
            {
                "arifle_AKS_F",
                "",
                90000,
                -1,
                ""
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                240000,
                -1,
                ""
            },
            {
                "arifle_SDAR_F",
                "",
                120000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_SPAR_01_khk_F",
                "",
                260000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_SPAR_01_snd_F",
                "",
                260000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_SPAR_02_khk_F",
                "",
                420000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_SPAR_02_snd_F",
                "",
                420000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_Mk20_F",
                "",
                140000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_Mk20C_F",
                "",
                160000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_TRG20_F",
                "",
                140000,
                -1,
                "license_civ_rebel2"
            },
            {
                "arifle_TRG21_F",
                "",
                160000,
                -1,
                "license_civ_rebel2"
            },
            {
                "LMG_03_F",
                "",
                900000,
                "-1",
                "license_civ_rebel4"
            },
            {
                "SMG_03_TR_hex",
                "",
                225000,
                -1,
                ""
            },
            {
                "SMG_03_TR_camo",
                "",
                225000,
                -1,
                ""
            },
            {
                "SMG_03_TR_khaki",
                "",
                225000,
                -1,
                ""
            },
            {
                "SMG_03C_TR_hex",
                "",
                105000,
                -1,
                ""
            },
            {
                "SMG_03C_TR_camo",
                "",
                105000,
                -1,
                ""
            },
            {
                "SMG_03C_TR_khaki",
                "",
                105000,
                -1,
                ""
            },
            {
                "SMG_03C_hex",
                "",
                105000,
                -1,
                ""
            },
            {
                "SMG_03C_camo",
                "",
                105000,
                -1,
                ""
            },
            {
                "SMG_03C_khaki",
                "",
                105000,
                -1,
                ""
            },
            {
                "arifle_CTAR_hex_F",
                "",
                240000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_CTAR_ghex_F",
                "",
                240000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_CTARS_hex_F",
                "",
                240000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_CTARS_ghex_F",
                "",
                240000,
                -1,
                "license_civ_rebel3"
            },
            {
                "srifle_DMR_07_hex_F",
                "",
                345000,
                "-1",
                "license_civ_rebel4"
            },
            {
                "srifle_DMR_07_ghex_F",
                "",
                345000,
                "-1",
                "license_civ_rebel4"
            },
            {
                "arifle_MXC_F",
                "",
                225000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_MXC_khk_F",
                "",
                225000,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_MX_F",
                "",
                247500,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MX_khk_F",
                "",
                247500,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MXM_F",
                "",
                292500,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MXM_khk_F",
                "",
                292500,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_Katiba_F",
                "",
                247500,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_Katiba_C_F",
                "",
                247500,
                -1,
                "license_civ_rebel3"
            },
            {
                "arifle_ARX_ghex_F",
                "",
                110000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_ARX_hex_F",
                "",
                330000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MSBS65_camo_F",
                "",
                330000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MSBS65_sand_F",
                "",
                285000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MSBS65_Mark_camo_F",
                "",
                315000,
                -1,
                "license_civ_rebel4"
            },
            {
                "arifle_MSBS65_Mark_sand_F",
                "",
                315000,
                -1,
                "license_civ_rebel4"
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                500,
                -1,
                ""
            },
            {
                "10Rnd_9x21_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Yellow_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag_Sand",
                "",
                500,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Sand_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Green_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_580x42_ghex_Mag_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "100Rnd_580x42_ghex_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_580x42_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_khaki_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Slug",
                "",
                100,
                -1,
                ""
            },
            {
                "6Rnd_12Gauge_Pellets",
                "",
                100,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_khaki_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "10Rnd_Mk14_762x51_Mag",
                "",
                1000,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Arid_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Lush_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                1200,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_ERCO_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_ERCO_snd_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco_ghex_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_SOS",
                "",
                100000,
                -1,
                "license_civ_rebel2"
            },
            {
                "optic_DMS",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "optic_DMS_ghex_F",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "bipod_01_F_blk",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_tan",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_hex",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_lush",
                "",
                22500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                3750,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                3750,
                -1,
                ""
            }
        };
    };
    class donatorgun {
        name = "Sklep Donatora";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "Medikit",
                "",
                25000,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            },
            {
                "hgun_ACPC2_F",
                "",
                18000,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                23000,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                18000,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Pistol_01_F",
                "",
                20000,
                -1,
                "call life_donator >= 1"
            },
            {
                "hgun_Rook40_F",
                "",
                20000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_01_F",
                "",
                60000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_02_F",
                "",
                45000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_05_F",
                "",
                60000,
                -1,
                "call life_donator >= 1"
            },
            {
                "arifle_AKS_F",
                "",
                90000,
                -1,
                "call life_donator >= 1"
            },
            {
                "arifle_SDAR_F",
                "",
                120000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_SPAR_01_khk_F",
                "",
                260000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_SPAR_01_snd_F",
                "",
                260000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_SPAR_02_khk_F",
                "",
                420000,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_SPAR_02_snd_F",
                "",
                420000,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_Mk20_F",
                "",
                160000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_Mk20C_F",
                "",
                140000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_TRG20_F",
                "",
                140000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_TRG21_F",
                "",
                160000,
                -1,
                "call life_donator >= 2"
            },
            {
                "LMG_03_F",
                "",
                900000,
                -1,
                "call life_donator >= 4"
            },
            {
                "SMG_03_TR_hex",
                "",
                225000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03_TR_camo",
                "",
                225000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03_TR_khaki",
                "",
                225000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_TR_hex",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_TR_camo",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_TR_khaki",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_hex",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_camo",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "SMG_03C_khaki",
                "",
                105000,
                -1,
                "call life_donator >= 1"
            },
            {
                "arifle_CTAR_hex_F",
                "",
                240000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_CTAR_ghex_F",
                "",
                240000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_CTARS_hex_F",
                "",
                240000,
                -1,
                "call life_donator >= 2"
            },
            {
                "arifle_CTARS_ghex_F",
                "",
                240000,
                -1,
                "call life_donator >= 2"
            },
            {
                "srifle_DMR_07_hex_F",
                "",
                345000,
                -1,
                "call life_donator >= 4"
            },
            {
                "srifle_DMR_07_ghex_F",
                "",
                345000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MXC_F",
                "",
                225000,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_MXC_khk_F",
                "",
                225000,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_MX_F",
                "",
                247500,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MX_khk_F",
                "",
                247500,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MXM_F",
                "",
                292500,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MXM_khk_F",
                "",
                292500,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_Katiba_F",
                "",
                247500,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_Katiba_C_F",
                "",
                247500,
                -1,
                "call life_donator >= 3"
            },
            {
                "arifle_ARX_ghex_F",
                "",
                330000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_ARX_hex_F",
                "",
                330000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MSBS65_camo_F",
                "",
                285000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MSBS65_sand_F",
                "",
                285000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MSBS65_Mark_camo_F",
                "",
                315000,
                -1,
                "call life_donator >= 4"
            },
            {
                "arifle_MSBS65_Mark_sand_F",
                "",
                315000,
                -1,
                "call life_donator >= 4"
            },
        };
        mags[] = {
            {
                "11Rnd_45ACP_Mag",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Yellow_Mag",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                175,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                650,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                750,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag_Sand",
                "",
                750,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Sand_Mag_Tracer_F",
                "",
                1500,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Green_Mag_Tracer_F",
                "",
                1500,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                800,
                -1,
                ""
            },
            {
                "30Rnd_580x42_Mag_F",
                "",
                750,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                750,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                800,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_khaki_mag",
                "",
                800,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                800,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                800,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_khaki_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "20Rnd_762x51_Mag",
                "",
                1000,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Arid_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Lush_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "75rnd_762x39_AK12_Lush_Mag_F",
                "",
                1900,
                -1,
                ""
            },
            {
                "75rnd_762x39_AK12_Arid_Mag_F",
                "",
                1900,
                -1,
                ""
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                1900,
                -1,
                ""
            },
            {
                "RPG7_F",
                "",
                450000,
                -1,
                ""
            },
            {
                "RPG32_F",
                "",
                750000,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_ERCO_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_ERCO_snd_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco_ghex_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_SOS",
                "",
                100000,
                -1,
                "call life_donator >= 3"
            },
            {
                "optic_DMS",
                "",
                150000,
                -1,
                "call life_donator >= 4"
            },
            {
                "optic_DMS_ghex_F",
                "",
                150000,
                -1,
                "call life_donator >= 4"
            },
            {
                "bipod_01_F_blk",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_tan",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_hex",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_lush",
                "",
                22500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                3750,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                3750,
                -1,
                ""
            }
        };
    };
    class genstore {
        name = "Sklep Techniczny";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                100,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
    class f_station_store {
        name = "Stacja Benzynowa";
        side = "";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                100,
                -1,
                ""
            },
            {
                "NVGoggles",
                "",
                2500,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
    class cop_basic {
        name = "Sklep Policyjny";
        side = "cop";
        conditions = "";
        items[] = {
            {
                "Binocular",
                "",
                1,
                -1,
                ""
            },
            {
                "Rangefinder",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                1,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1,
                -1,
                ""
            },
            {
                "NVGoggles_OPFOR",
                "",
                1,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                1000,
                -1,
                ""
            },
            {
                "HandGrenade_Stone",
                "Flashbang",
                3000,
                -1,
                ""
            },
            {
                "SmokeShellBlue",
                "Gaz łzawiący",
                3000,
                -1,
                ""
            },
            {
                "hgun_P07_snds_F",
                "Tazer",
                3000,
                -1,
                ""
            },
            {
                "hgun_P07_blk_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_P07_khk_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_01_green_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_Pistol_01_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_Rook40_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "hgun_Pistol_heavy_02_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "SMG_01_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "SMG_02_F",
                "",
                15000,
                -1,
                ""
            },
            {
                "SMG_05_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "arifle_SDAR_F",
                "",
                40000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "arifle_TRG21_F",
                "",
                53000,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "arifle_Mk20_F",
                "",
                53000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "SMG_03_black",
                "",
                75000,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                80000,
                -1,
                "call life_coplevel >=3"
            },
            {
                "arifle_SPAR_01_blk_F",
                "",
                86000,
                -1,
                "call life_coplevel >= 5"
            },
            {
                "arifle_SPAR_02_blk_F",
                "",
                140000,
                -1,
                "call life_coplevel >= 6"
            },
            {
                "LMG_03_F",
                "",
                300000,
                -1,
                "call life_coplevel >= 11"
            },
            {
                "arifle_CTARS_blk_F",
                "",
                80000,
                -1,
                "call life_coplevel >= 4"
            },
            {
                "arifle_MX_Black_F",
                "",
                82000,
                -1,
                "call life_coplevel >= 7"
            },
            {
                "arifle_MXM_Black_F",
                "",
                97000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "arifle_MSBS65_black_F",
                "",
                95000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "arifle_MSBS65_Mark_black_F",
                "",
                105000,
                -1,
                "call life_coplevel >= 8"
            },
            {
                "srifle_DMR_07_blk_F",
                "",
                115000,
                -1,
                "call life_coplevel >= 10"
            },
            {
                "arifle_ARX_blk_F",
                "",
                110000,
                -1,
                "call life_coplevel >= 9"
            },
            {
                "arifle_Katiba_F",
                "",
                82000,
                -1,
                "call life_coplevel >= 7"
            },
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_9x21_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "6Rnd_45ACP_Cylinder",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_556x45_Box_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_65x39_cased_Box",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_762x51_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HEAT_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HEAT55_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HE_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_HE_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "Titan_AA",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_93x64_DMR_05_Mag",
                "",
                10000,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                "call life_coplevel >=1"
            },
            {
                "2Rnd_12Gauge_Slug",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            },
            {
                "6Rnd_12Gauge_Pellets",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            }
        };
        accs[] = {
            {
                "optic_MRD_black",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_MRD",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Yorris",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Aco",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Holosight",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Holosight_smg",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_ACO_grn_smg",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Arco_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_Hamr",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_MRCO",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_ERCO_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "optic_DMS",
                "",
                100,
                -1,
                "call life_coplevel >= 2"
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "muzzle_snds_acp",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_L",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_M",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_570",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_H",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_58_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_65_TI_blk_F",
                "",
                100,
                -1,
                "call life_coplevel >= 3"
            },
            {
                "muzzle_snds_B",
                "",
                100,
                -1,
                "call life_coplevel >= 5"
            },
        };
    };
    class swat_basic {
        name = "Sklep SWAT";
        side = "cop";
        conditions = "license_cop_cSwat";
        items[] = {
            {
                "Binocular",
                "",
                1,
                -1,
                ""
            },
            {
                "Rangefinder",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemGPS",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemMap",
                "",
                1,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                1,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1,
                -1,
                ""
            },
            {
                "NVGoggles_OPFOR",
                "",
                1,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                1000,
                -1,
                ""
            },
            {
                "HandGrenade_Stone",
                "Flashbang",
                3000,
                -1,
                ""
            },
            {
                "SmokeShellBlue",
                "Gaz łzawiący",
                3000,
                -1,
                ""
            },
            {
                "hgun_P07_snds_F",
                "Paralizator",
                3000,
                -1,
                ""
            },
            {
                "SMG_01_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "SMG_02_F",
                "",
                15000,
                -1,
                ""
            },
            {
                "SMG_05_F",
                "",
                20000,
                -1,
                ""
            },
            {
                "arifle_SDAR_F",
                "",
                40000,
                -1,
                ""
            },
            {
                "arifle_TRG21_F",
                "",
                53000,
                -1,
                ""
            },
            {
                "arifle_Mk20_F",
                "",
                53000,
                -1,
                ""
            },
            {
                "SMG_03_black",
                "",
                75000,
                -1,
                ""
            },
            {
                "sgun_HunterShotgun_01_F",
                "",
                80000,
                -1,
                ""
            },
            {
                "arifle_SPAR_01_blk_F",
                "",
                86000,
                -1,
                ""
            },
            {
                "arifle_SPAR_02_blk_F",
                "",
                140000,
                -1,
                ""
            },
            {
                "LMG_03_F",
                "",
                300000,
                -1,
                ""
            },
            {
                "arifle_CTARS_blk_F",
                "",
                80000,
                -1,
                ""
            },
            {
                "arifle_MX_Black_F",
                "",
                82000,
                -1,
                ""
            },
            {
                "arifle_MX_SW_Black_F",
                "",
                1,
                -1,
                ""
            },
            {
                "arifle_MXM_Black_F",
                "",
                97000,
                -1,
                ""
            },
            {
                "arifle_MSBS65_black_F",
                "",
                95000,
                -1,
                ""
            },
            {
                "arifle_MSBS65_Mark_black_F",
                "",
                105000,
                -1,
                ""
            },
            {
                "srifle_DMR_07_blk_F",
                "",
                115000,
                -1,
                ""
            },
            {
                "arifle_ARX_blk_F",
                "",
                110000,
                -1,
                ""
            },
            {
                "arifle_Katiba_F",
                "",
                82000,
                -1,
                ""
            },
            {
                "LMG_Mk200_black_F",
                "",
                1,
                -1,
                ""
            },
            {
                "srifle_DMR_06_hunter_F",
                "",
                1,
                -1,
                ""
            },
            {
                "srifle_DMR_06_hunter_khs_F",
                "",
                1,
                -1,
                ""
            },
            {
                "arifle_AK12U_F",
                "",
                1,
                -1,
                ""
            },
            {
                "arifle_AK12_F",
                "",
                1,
                -1,
                ""
            },
            {
                "75rnd_762x39_AK12_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                ""
            }
        };
        mags[] = {
            {
                "16Rnd_9x21_Mag",
                "",
                100,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "9Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "11Rnd_45ACP_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "150Rnd_556x45_Drum_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_556x45_Box_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_580x42_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "100Rnd_65x39_caseless_black_mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "200Rnd_65x39_cased_Box",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "20Rnd_762x51_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "75Rnd_762x39_Mag_F",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_762x54_Mag",
                "",
                100,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HEAT_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HEAT55_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "MRAWS_HE_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "RPG32_HE_F",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "Titan_AA",
                "",
                50000,
                -1,
                "call life_coplevel >= 1"
            },
            {
                "10Rnd_93x64_DMR_05_Mag",
                "",
                10000,
                -1,
                ""
            },
            {
                "2Rnd_12Gauge_Pellets",
                "",
                500,
                -1,
                "call life_coplevel >=1"
            },
            {
                "2Rnd_12Gauge_Slug",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            },
            {
                "6Rnd_12Gauge_Pellets",
                "",
                100,
                -1,
                "call life_coplevel >=1"
            }
        };
        accs[] = {
            {
                "muzzle_snds_L",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_M",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_H",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_ACO_grn_smg",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_B",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                100,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                100,
                -1,
                ""
            },
            {
                "bipod_01_F_blk",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Arco_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_ERCO_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "optic_DMS",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_65_TI_blk_F",
                "",
                100,
                -1,
                ""
            },
            {
                "muzzle_snds_570",
                "",
                100,
                -1,
                ""
            }
        };
    };
    class med_basic {
        name = "Sklep Medyczny";
        side = "med";
        conditions = "";
        items[] = {
            {
                "ItemGPS",
                "",
                100,
                -1,
                ""
            },
            {
                "Binocular",
                "",
                100,
                -1,
                ""
            },
            {
                "FirstAidKit",
                "",
                1000,
                -1,
                ""
            },
            {
                "NVGoggles_INDEP",
                "",
                2500,
                -1,
                ""
            },
            {
                "ItemRadio",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemCompass",
                "",
                100,
                -1,
                ""
            },
            {
                "ItemWatch",
                "",
                100,
                -1,
                ""
            },
            {
                "Medikit",
                "",
                5000,
                -1,
                ""
            }
        };
        mags[] = {};
        accs[] = {};
    };
    class b_market {
        name = "Czarny rynek";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "arifle_MX_SW_F",
                "",
                10,
                -1,
                ""
            },
            {
                "arifle_MX_SW_khk_F",
                "",
                10,
                -1,
                ""
            },
            {
                "LMG_Mk200_F",
                "",
                12,
                -1,
                ""
            },
            {
                "srifle_DMR_06_hunter_F",
                "",
                20,
                -1,
                ""
            },
            {
                "srifle_DMR_06_hunter_khs_F",
                "",
                20,
                -1,
                ""
            },
            {
                "arifle_AKM_F",
                "",
                15,
                -1,
                ""
            },
            {
                "arifle_AK12U_lush_F",
                "",
                15,
                -1,
                ""
            },
            {
                "arifle_AK12U_arid_F",
                "",
                15,
                -1,
                ""
            },
            {
                "arifle_AK12_lush_F",
                "",
                15,
                -1,
                ""
            },
            {
                "arifle_AK12_arid_F",
                "",
                15,
                -1,
                ""
            },
        };
        mags[] = {
            {
                "11Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Yellow_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag_Sand",
                "",
                500,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Sand_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Green_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_580x42_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_khaki_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_khaki_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "10Rnd_Mk14_762x51_Mag",
                "",
                1000,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Arid_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Lush_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                1200,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_ERCO_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_ERCO_snd_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco_ghex_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_SOS",
                "",
                100000,
                -1,
                "license_civ_rebel2"
            },
            {
                "optic_DMS",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "optic_DMS_ghex_F",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "bipod_01_F_blk",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_tan",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_hex",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_lush",
                "",
                22500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                3750,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                3750,
                -1,
                ""
            }
        };
    };
    class b_market2 {
        name = "Czarny rynek";
        side = "civ";
        conditions = "";
        items[] = {
            {
                "arifle_MX_SW_F",
                "",
                550000,
                -1,
                "license_civ_bm_mx"
            },
            {
                "arifle_MX_SW_khk_F",
                "",
                550000,
                -1,
                "license_civ_bm_mx"
            },
            {
                "LMG_Mk200_F",
                "",
                700000,
                -1,
                "license_civ_bm_mk200"
            },
            {
                "srifle_DMR_06_hunter_F",
                "",
                800000,
                -1,
                "license_civ_bm_mk14"
            },
            {
                "srifle_DMR_06_hunter_khs_F",
                "",
                800000,
                -1,
                "license_civ_bm_mk14"
            },
            {
                "arifle_AKM_F",
                "",
                500000,
                -1,
                "license_civ_bm_ak"
            },
            {
                "arifle_AK12U_lush_F",
                "",
                550000,
                -1,
                "license_civ_bm_ak"
            },
            {
                "arifle_AK12U_arid_F",
                "",
                550000,
                -1,
                "license_civ_bm_ak"
            },
            {
                "arifle_AK12_lush_F",
                "",
                600000,
                -1,
                "license_civ_bm_ak"
            },
            {
                "arifle_AK12_arid_F",
                "",
                600000,
                -1,
                "license_civ_bm_ak"
            },
        };
        mags[] = {
            {
                "11Rnd_45ACP_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_45ACP_Mag_SMG_01",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Yellow_Mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_9x21_Mag_SMG_02_Tracer_Red",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_545x39_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_556x45_UW_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_556x45_Stanag_Sand",
                "",
                500,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Sand_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "150Rnd_556x45_Drum_Green_Mag_Tracer_F",
                "",
                3000,
                -1,
                ""
            },
            {
                "200Rnd_556x45_Box_Tracer_F",
                "",
                2500,
                -1,
                ""
            },
            {
                "50Rnd_570x28_SMG_03",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_580x42_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "20Rnd_650x39_Cased_Mag_F",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_green",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_khaki_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "30Rnd_65x39_caseless_msbs_mag",
                "",
                500,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_khaki_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "100Rnd_65x39_caseless_mag",
                "",
                1800,
                -1,
                ""
            },
            {
                "10Rnd_Mk14_762x51_Mag",
                "",
                1000,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Arid_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30rnd_762x39_AK12_Lush_Mag_F",
                "",
                1200,
                -1,
                ""
            },
            {
                "30Rnd_762x39_Mag_F",
                "",
                1200,
                -1,
                ""
            }
        };
        accs[] = {
            {
                "optic_ACO_grn",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Aco_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_Holosight_smg",
                "",
                15000,
                -1,
                ""
            },
            {
                "optic_ERCO_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_ERCO_snd_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Hamr_khk_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_Arco_ghex_F",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_MRCO",
                "",
                45000,
                -1,
                ""
            },
            {
                "optic_SOS",
                "",
                100000,
                -1,
                "license_civ_rebel2"
            },
            {
                "optic_DMS",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "optic_DMS_ghex_F",
                "",
                150000,
                -1,
                "license_civ_rebel4"
            },
            {
                "bipod_01_F_blk",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_tan",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_hex",
                "",
                22500,
                -1,
                ""
            },
            {
                "bipod_02_F_lush",
                "",
                22500,
                -1,
                ""
            },
            {
                "acc_pointer_IR",
                "",
                3750,
                -1,
                ""
            },
            {
                "acc_flashlight",
                "",
                3750,
                -1,
                ""
            }
        };
    };
};